[package]
name = "bakfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
colored = "2.0.1"
dirs = "5.0.1"
itertools = "0.11.0"
lazy_static = "1.4.0"
regex = "1.9.0"
